services:
  curator_mongo:
    image: mongo:${MONGO_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_cdcs_mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
    volumes:
      - mongo_data:/data/db/
      - ./mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    command: "--auth --noscripting"

volumes:
  mongo_data:
