services:
  curator_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_cdcs_elasticsearch
    environment:
      - node.name=${COMPOSE_PROJECT_NAME}_cdcs_elasticsearch
      - discovery.seed_hosts=${COMPOSE_PROJECT_NAME}_cdcs_elasticsearch
      - cluster.initial_master_nodes=${COMPOSE_PROJECT_NAME}_cdcs_elasticsearch
      - cluster.name=docker-cluster
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
